arrowParens: 'avoid'
endOfLine: 'lf'
printWidth: 120
semi: true
singleQuote: true
trailingComma: 'none'
tabWidth: 2
useTabs: false
overrides:
  - files: '*.html'
    options:
      parser: 'html'
  - files: '*.component.html'
    options:
      parser: 'angular'
importOrder:
  - '^@angular/(.*)$'
  - '<THIRD_PARTY_MODULES>'
  - '^[src/]'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins:
  - classProperties
  - typescript
  - jsx
  - decorators-legacy
